services:
  - type: web
    name: trustboxhedera-backend
    runtime: node
    rootDir: packages/backend
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: HEDERA_NETWORK
        value: testnet
      - key: HEDERA_RPC_URL
        value: https://testnet.hashio.io/api
      - key: HEDERA_CHAIN_ID
        value: "296"
      - key: FRONTEND_URL
        value: https://trustbox-omega.vercel.app
      - key: TRUST_REGISTRY_ADDR
        value: "0x7Dd290DaF02F98d3d583fb35540c5d78dDeCEcbA"
      - key: AUDIT_REGISTRY_ADDR
        value: "0x1FBEA692383bEAB0843c72Dd8dA712c935AbFA06"
      - key: AGENT_MARKETPLACE_ADDR
        value: "0xa36f7E1DC41a62A5C0E9074C61F5C471a6F53d0c"
      - key: INTENT_VAULT_ADDR
        value: "0xa39BD8F5Fb7CA64BFD3632A43C7bBBE6D4152129"
      - key: HOL_REGISTRY_URL
        value: https://moonscape.tech
      - key: PINATA_GATEWAY
        value: https://gateway.pinata.cloud
      - key: PHALA_ENDPOINT
        value: https://api.phala.network/api/contract/dispatch
      - key: JWT_SECRET
        sync: false
      - key: HEDERA_OPERATOR_ID
        sync: false
      - key: HEDERA_OPERATOR_KEY
        sync: false
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
      - key: HCS_AUDIT_TOPIC_ID
        sync: false
      - key: HCS_INTENT_TOPIC_ID
        sync: false
      - key: HCS_AGENT_TOPIC_ID
        sync: false
      - key: HCS_BLINDAUDIT_TOPIC_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PINATA_JWT
        sync: false
